version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ .Revision }}

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradlew
          key: v1-dependencies-{{ .Branch }}-{{ .Revision }}

      - run: ./gradle clean check

      - run:
          name: Save test results
          command: |
            mkdir -p /tmp/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} /tmp/test-results/junit/ \;
          when: always

      - store_test_results:
          path: /tmp/test-results
